package pojos;
// Generated 20-ene-2020 9:26:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private short id;
     private String nombre;
     private String descripcion;
     private String guarnicion;
     private Set productos = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(short id) {
        this.id = id;
    }
    public Categoria(short id, String nombre, String descripcion, String guarnicion, Set productos) {
       this.id = id;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.guarnicion = guarnicion;
       this.productos = productos;
    }
   
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getGuarnicion() {
        return this.guarnicion;
    }
    
    public void setGuarnicion(String guarnicion) {
        this.guarnicion = guarnicion;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


